version: '3.8'
services:
  server:
    image: laravel_image:v6
    tty: true
    restart: always
    environment:
      DEVELOPMENT: 'true'
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/logs:/var/log/nginx/
      - ./app:/var/www/html
      - ./php/www.conf:/etc/php/8.3/fpm/pool.d/www.conf
      - ./php/php.ini:/etc/php/8.3/fpm/php.ini
    depends_on:
      - db
  db:
     image: mysql:9.3.0
     ports:
       - "3310:3306"
     environment:
          MYSQL_DATABASE: saas-subscription-api
          MYSQL_USER: temp_user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test2
     volumes:
          - ./app/storage/mysql:/var/lib/mysql
     networks:
          - default
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:5.2.2
     depends_on:
          - db
     ports:
          - 9902:80
     environment:
          MYSQL_USER: temp_user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test2
          UPLOAD_LIMIT: 1024M