name: CI Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ci_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, sqlite, mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHP-CS-Fixer (lint)
        run: ./storage/vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Set up application key
        run: php artisan key:generate

      - name: Prepare SQLite file-based DB
        run: |
          mkdir -p storage/database
          touch storage/database/database.sqlite

      - name: Run migrations (for SQLite in-memory)
        run: php artisan migrate --env=testing

      - name: Run PHPUnit tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: ./storage/vendor/bin/phpunit